version: "3.5"
services:
  database:
    container_name: chinese-flashcards-database
    env_file: .env
    image: postgres
    restart: always
    networks:
      - chinese-flashcards
    ports:
      - 5432:5432

  app:
    image: chinese-flashcards-app
    tty: true
    container_name: chinese-flashcards-app
    env_file: .env
    restart: always
    build: 
      context: .
    links:
      - database:database
    ports:
      - 3000:3000
    volumes:
      - .:/chinese-flashcards-app
    networks:
      - chinese-flashcards

networks:
  chinese-flashcards:
    external:
      name: chinese-flashcards
