default: &default
  adapter: postgresql
  host: <%= ENV.fetch("FLASHCARDS_POSTGRES_HOST") %>
  pool: <%= ENV.fetch("FLASHCARDS_RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  username: <%= ENV.fetch("FLASHCARDS_POSTGRES_USER") %>
  password: <%= ENV.fetch("FLASHCARDS_POSTGRES_PASSWORD") %>
  port: <%= ENV.fetch("FLASHCARDS_POSTGRES_PORT") %>


development:
  <<: *default
  database: chinese_flashcards_development

test:
  <<: *default
  database: chinese_flashcards_test

production:
  <<: *default
  database: chinese_flashcards_production
